# Generated by Django 5.0.5 on 2024-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('banking', '0007_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
