# Generated by Django 5.0.5 on 2024-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
